version: '3'
services:
  app:
    image: ghcr.io/baonq243/commandlinefubot:latest
    volumes:
      - ./app:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CHAT_ID
      - TOKEN